// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DrizzleDrizzleMigration struct {
	ID        int32  `json:"id"`
	Hash      string `json:"hash"`
	CreatedAt *int64 `json:"created_at"`
}

type ImageComponent struct {
	ID                 uuid.UUID          `json:"id"`
	WebsiteComponentID uuid.UUID          `json:"website_component_id"`
	ImageID            uuid.UUID          `json:"image_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Version            int32              `json:"version"`
}

type SchemaMigration struct {
	Version int64 `json:"version"`
	Dirty   bool  `json:"dirty"`
}

type SimpleTextComponent struct {
	ID                 uuid.UUID          `json:"id"`
	WebsiteComponentID uuid.UUID          `json:"website_component_id"`
	Locale             string             `json:"locale"`
	Content            string             `json:"content"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Version            int32              `json:"version"`
}

type Website struct {
	ID            uuid.UUID          `json:"id"`
	Handle        string             `json:"handle"`
	DefaultLocale string             `json:"default_locale"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Version       int32              `json:"version"`
}

type WebsiteComponent struct {
	ID            uuid.UUID          `json:"id"`
	WebsiteID     uuid.UUID          `json:"website_id"`
	WebsitePageID uuid.UUID          `json:"website_page_id"`
	SortKey       string             `json:"sort_key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Version       int32              `json:"version"`
}

type WebsiteContent struct {
	ID                        uuid.UUID          `json:"id"`
	WebsiteID                 uuid.UUID          `json:"website_id"`
	Locale                    string             `json:"locale"`
	WebsiteDisplayName        *string            `json:"website_display_name"`
	WebsiteDisplayDescription *string            `json:"website_display_description"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	Version                   int32              `json:"version"`
}

type WebsitePage struct {
	ID        uuid.UUID          `json:"id"`
	WebsiteID uuid.UUID          `json:"website_id"`
	UrlSlug   string             `json:"url_slug"`
	SortKey   string             `json:"sort_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Version   int32              `json:"version"`
}

type WebsitePageContent struct {
	ID            uuid.UUID          `json:"id"`
	WebsitePageID uuid.UUID          `json:"website_page_id"`
	Locale        string             `json:"locale"`
	Title         *string            `json:"title"`
	Subtitle      *string            `json:"subtitle"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Version       int32              `json:"version"`
}
