// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateWebsiteComponent(ctx context.Context, arg CreateWebsiteComponentParams) (WebsiteComponent, error)
	CreateWebsitePage(ctx context.Context, arg CreateWebsitePageParams) (WebsitePage, error)
	GetImageComponentsByWebsiteID(ctx context.Context, websiteID uuid.UUID) ([]GetImageComponentsByWebsiteIDRow, error)
	GetTextComponentsByWebsiteID(ctx context.Context, arg GetTextComponentsByWebsiteIDParams) ([]GetTextComponentsByWebsiteIDRow, error)
	GetWebsiteByComponentID(ctx context.Context, id uuid.UUID) (GetWebsiteByComponentIDRow, error)
	GetWebsiteByHandle(ctx context.Context, handle string) (GetWebsiteByHandleRow, error)
	GetWebsiteByID(ctx context.Context, id uuid.UUID) (GetWebsiteByIDRow, error)
	GetWebsiteByPageID(ctx context.Context, id uuid.UUID) (GetWebsiteByPageIDRow, error)
	GetWebsiteComponentsByWebsitePageID(ctx context.Context, websitePageID uuid.UUID) ([]GetWebsiteComponentsByWebsitePageIDRow, error)
	GetWebsiteContentByWebsiteID(ctx context.Context, arg GetWebsiteContentByWebsiteIDParams) (GetWebsiteContentByWebsiteIDRow, error)
	GetWebsiteImageComponent(ctx context.Context, id uuid.UUID) (GetWebsiteImageComponentRow, error)
	GetWebsitePageByID(ctx context.Context, arg GetWebsitePageByIDParams) (GetWebsitePageByIDRow, error)
	GetWebsitePagesByWebsiteID(ctx context.Context, arg GetWebsitePagesByWebsiteIDParams) ([]GetWebsitePagesByWebsiteIDRow, error)
	GetWebsiteTextComponent(ctx context.Context, arg GetWebsiteTextComponentParams) (GetWebsiteTextComponentRow, error)
	UpdateWebsiteComponent(ctx context.Context, arg UpdateWebsiteComponentParams) (WebsiteComponent, error)
	UpdateWebsitePage(ctx context.Context, arg UpdateWebsitePageParams) (WebsitePage, error)
	UpdateWebsiteTextComponent(ctx context.Context, arg UpdateWebsiteTextComponentParams) (SimpleTextComponent, error)
	UpsertWebsitePageContent(ctx context.Context, arg UpsertWebsitePageContentParams) (WebsitePageContent, error)
	UpsertWebsiteQandAComponent(ctx context.Context, arg UpsertWebsiteQandAComponentParams) (ImageComponent, error)
	// -- name: CreateWebsiteQandAComponent :one
	// INSERT INTO simple_qanda_component (website_component_id, locale, question, answer, firebase_key, firebase_ref)
	// VALUES (sqlc.arg(website_component_id), sqlc.arg(locale), sqlc.narg(question), sqlc.narg(answer), sqlc.narg(firebase_key), sqlc.narg(firebase_ref)) RETURNING *;
	// -- name: UpdateWebsiteQandAComponent :one
	// UPDATE simple_qanda_component SET
	//     question = coalesce(sqlc.narg(question), simple_qanda_component.question),
	//     answer = coalesce(sqlc.narg(answer), simple_qanda_component.answer),
	//     firebase_key = coalesce(sqlc.narg(firebase_key), simple_qanda_component.firebase_key),
	//     firebase_ref = coalesce(sqlc.narg(firebase_ref), simple_qanda_component.firebase_ref),
	//     updated_at = now(),
	//     version = simple_qanda_component.version + 1
	// WHERE website_component_id = sqlc.arg(website_component_id)
	// AND locale = sqlc.arg(locale) RETURNING *;
	UpsertWebsiteSimpleTextComponent(ctx context.Context, arg UpsertWebsiteSimpleTextComponentParams) (SimpleTextComponent, error)
}

var _ Querier = (*Queries)(nil)
